### Get list of comments under the specified post
GET {{baseUrl}}/posts/2/comments?limit=5

### Create comment
POST {{baseUrl}}/comments
Content-Type: application/json

{
    "content": "glorious",
    "author_id": 1,
    "post_id": 8
}
