### Get all posts
GET {{baseUrl}}/posts?sortBy=new

### Get paginated list of posts
GET {{baseUrl}}/posts?page=1&limit=2&sortBy=old

### Get post by ID
# @prompt id
GET {{baseUrl}}/posts/{{id}}

### Create post
POST {{baseUrl}}/posts
Content-Type: application/json

{
    "title": "test post with topics",
    "content": "test post with topics",
    "author_id": 1,
    "topic_ids": [1]
}

### Delete post
# @prompt id
DELETE {{baseUrl}}/posts/{{id}}

### Tag post with topics
# @prompt id
PUT {{baseUrl}}/posts/{{id}}/topics
Content-Type: application/json

{
    "topic_ids": [1, 2]
}
